### ISSUE TITLE
Error: setState() called after dispose() when rive animation is shown briefly

### ISSUE THREAD

**Issue by JonasKuschel** [rive-app/rive-flutter#159]
### Description
I am trying to use a rive animation as a loading screen. Sometimes the loading time is very short, so its creation is cancelled before it can start the animation. Because of that it throws an setState() called after dispose() error.

### Steps To Reproduce

Make rive animation appear for a very short period of time:
```
import 'package:flutter/material.dart';
import 'package:rive/rive.dart';

class LoadingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Container(
        height: 250,
        width: 250,
        decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(24),
            color: Colors.black,
            ),
        child: const RiveAnimation.asset(
          'assets/animations/loading_animation.riv',
          animations: ['Ticking Animation'],
        ),
      ),
    );
  }
}
```

#### Source `.riv`/`.rev` file
if you need the source file I can send you a gist

### Expected behavior
The rive animation should be shown without showing this error.

### Device & Versions (please complete the following information)
- Device: Chrome
- OS: MacOS 11.5
- Flutter Version: 
```
Flutter 2.2.3 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (vor 5 Wochen) • 2021-07-01
12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
```

#### Error

<details>
  <summary>Click to expand</summary>

```
Error: setState() called after dispose(): _RiveAnimationState#a50c1(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#e8925(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#f69bb(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#2b7f6(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#70d8f(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#90638(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
Error: setState() called after dispose(): _RiveAnimationState#a1f6a(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:5041:11)
    at http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17176:23
    at rive_animation._RiveAnimationState.new.setState (http://localhost:5000/packages/flutter/src/widgets/widget_span.dart.lib.js:17182:28)
    at rive_animation._RiveAnimationState.new.[_init] (http://localhost:5000/packages/rive/src/widgets/rive_animation.dart.lib.js:1467:12)
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
```

</details>

**Comment by ihadabs** [comment]
Same here ^^.

**Comment by JonasKuschel** [comment]
I am using kDebugMode to not spam my debug console while developing:
```
Container(
child: kDebugMode
            ? const CircularProgressIndicator()
            : const RiveAnimation.asset(
                'assets/animations/loading_animation.riv',
                animations: ['Ticking Animation'],
              ),
)
```

**Comment by luigi-rosso** [comment]
This is fixed is master or pub.dev version 0.7.30!
