### ISSUE TITLE
Can I change color (fill) of an element in code in rive ?

### ISSUE THREAD

**Issue by radha1990kumari** [rive-app/rive-flutter#164]

**Comment by haorendashu** [comment]
I want to do that, too

**Comment by goranesine** [comment]
I am interested..

**Comment by falc0n33** [comment]
@radha1990kumari @haorendashu @goranesine 
Check out this snippet.

```
       RiveAnimation.asset(
          'assets/animations/voice.riv',
          fit: BoxFit.fitHeight,
          onInit: (Artboard artboard) {
            artboard.forEachComponent(
              (child) {
                if (child is Shape) {
                  final Shape shape = child;
                  shape.fills.first.paint.color = Colors.red;
                }
              },
            );
          },
        )
 ```

**Comment by goranesine** [comment]
Nice,thanks..

**Comment by radha1990kumari** [comment]
> @radha1990kumari @haorendashu @goranesine Check out this snippet.
> 
> ```
>        RiveAnimation.asset(
>           'assets/animations/voice.riv',
>           fit: BoxFit.fitHeight,
>           onInit: (Artboard artboard) {
>             artboard.forEachComponent(
>               (child) {
>                 if (child is Shape) {
>                   final Shape shape = child;
>                   shape.fills.first.paint.color = Colors.red;
>                 }
>               },
>             );
>           },
>         )
> ```

@falc0n33 I get this error  , the `.riv` file I am using is this https://rive.app/community/877-1781-football-time/
```
E/flutter (16169): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: No element
E/flutter (16169): #0      _CompactLinkedHashSet.first (dart:collection-patch/compact_hash.dart:511:5)
E/flutter (16169): #1      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:rive_test/main.dart:266:45)
E/flutter (16169): #2      SetMixin.forEach (dart:collection/set.dart:142:30)
E/flutter (16169): #3      Artboard.forEachComponent (package:rive/src/rive_core/artboard.dart:75:19)
E/flutter (16169): #4      _MyHomePageState.build.<anonymous closure> (package:rive_test/main.dart:262:36)
E/flutter (16169): #5      _RiveAnimationState._init (package:rive/src/widgets/rive_animation.dart:141:20)
E/flutter (16169): #6      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (16169): #7      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (16169): <asynchronous suspension>
```

**Comment by zplata** [comment]
There isn't a great API to dynamically modify attributes like fills and strokes yet to certain components of a Rive creation, but the below should help.

`(shape.fills.first.children[0] as SolidColor).colorValue = (Colors.yellow).value;`

**Comment by TaniaMagdieva** [comment]
> There isn't a great API to dynamically modify attributes like fills and strokes yet to certain components of a Rive creation, but the below should help.
> 
> `(shape.fills.first.children[0] as SolidColor).colorValue = (Colors.yellow).value;`

Is something like that can be used for the visibility of the layer?

**Comment by TaniaMagdieva** [comment]
If the layer is the shape/element is something like that can be used for the visibility of the layer?

**Comment by zplata** [comment]
@TaniaMagdieva You might be able to achieve this effect by setting the `opacity` property (`double`).

**Comment by HayesGordon** [comment]
I made an example showing how to set the colour at runtime using a custom Rive render object. This is the more advanced approach but will give you more control. This particular example will also respect the opacity (alpha) value of fills for animations where the colour is being changed.

https://github.com/HayesGordon/rive_flutter_runtime_color_change_example

**Comment by rafid08** [comment]
I would like to set image URL dynamically?
Is this even possible?

**Comment by gabrielchaves7** [comment]
Another (pretty ugly) option is to do something like this at the onInit callback. Different components can have different ways to set the color. For example, there is some components where you need to call component.fill.color, and others where component.color do the trick. You can figure this out by debugging. 
```
artboard.forEachComponent((component) {
        try {
          if ((component as dynamic).color != null) {
            (component as dynamic).color = widget.color;
          }
        } catch (e) {}
      });
```

**Comment by HayesGordon** [comment]
The recommended way to update colors (and all Rive properties) is to use our new feature, [Data Binding](https://rive.app/docs/runtimes/data-binding).

This requires updating to the latest major version `0.14.0-dev.1`

You can read more here:
- [Migration Guide](https://rive.app/docs/runtimes/flutter/migration-guide)
- [Rive Native for Flutter](https://rive.app/docs/runtimes/flutter/rive-native)
- [Rive Flutter Docs](https://rive.app/docs/runtimes/flutter/flutter)

If you're having issues updating to the latest, please open a new issue with reproducible steps.
