### ISSUE TITLE
Animation not run in flutter when included png files in the animations. 

### ISSUE THREAD

**Issue by EshanNimesha01** [rive-app/rive-flutter#197]
Error: FormatException: Unexpected extension byte (at offset 0)
    at Object.throw_ [as throw] (http://localhost:57198/dart_sdk.js:5063:11)
    at convert._Utf8Decoder.new.convertGeneral (http://localhost:57198/dart_sdk.js:50399:19)
    at convert._Utf8Decoder.new.convertSingle (http://localhost:57198/dart_sdk.js:50376:19)
    at Utf8Decoder.convert (http://localhost:57198/dart_sdk.js:50241:67)
    at binary_reader.BinaryReader.new.readString (http://localhost:57198/packages/rive/src/utilities/binary_buffer/binary_reader.dart.lib.js:148:38)
    at core_string_type.CoreStringType.new.deserialize (http://localhost:57198/packages/rive/src/core/field_types/core_string_type.dart.lib.js:16:21)
    at Object._skipProperty (http://localhost:57198/packages/rive/src/widgets/rive_animation.dart.lib.js:1929:11)
    at Object._readRuntimeObject (http://localhost:57198/packages/rive/src/widgets/rive_animation.dart.lib.js:1916:19)
    at new rive_file.RiveFile.__ (http://localhost:57198/packages/rive/src/widgets/rive_animation.dart.lib.js:1749:30)
    at Function.import (http://localhost:57198/packages/rive/src/widgets/rive_animation.dart.lib.js:1698:14)
    at asset (http://localhost:57198/packages/rive/src/widgets/rive_animation.dart.lib.js:1706:41)
    at asset.next (<anonymous>)
    at http://localhost:57198/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:57198/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:57198/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:57198/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:57198/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:57198/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57198/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:57198/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:57198/dart_sdk.js:40336:13)
    at http://localhost:57198/dart_sdk.js:35811:9

**Comment by manafn** [comment]
I'm facing this issue too

**Comment by manafn** [comment]
even svg , only layers created by rive works !!

**Comment by linzzzzllll** [comment]
I'm facing this issue too

**Comment by Ericahyana** [comment]
i have same issue 

```
E/flutter (27834): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Unexpected extension byte (at offset 0)
E/flutter (27834): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1787:7)
E/flutter (27834): #1      Utf8Decoder.convert (dart:convert/utf.dart:322:42)
E/flutter (27834): #2      BinaryReader.readString
package:rive/…/binary_buffer/binary_reader.dart:102
E/flutter (27834): #3      CoreStringType.deserialize
package:rive/…/field_types/core_string_type.dart:7
E/flutter (27834): #4      _skipProperty
package:rive/src/rive_file.dart:72
E/flutter (27834): #5      _readRuntimeObject
package:rive/src/rive_file.dart:54
E/flutter (27834): #6      new RiveFile._
package:rive/src/rive_file.dart:108
E/flutter (27834): #7      new RiveFile.import
package:rive/src/rive_file.dart:221
E/flutter (27834): #8      RiveFile.asset
package:rive/src/rive_file.dart:227
E/flutter (27834): <asynchronous suspension>

```

**Comment by ahmadyousafk** [comment]
I just solved this issue by changing the version of rive dependency from 0.7.26 to the latest 0.8.1.

**Comment by linzzzzllll** [comment]
> 我刚刚通过将依赖关系的版本从0.7.26更改为最新的0.8.1来解决此问题。

0.8.1 ?

**Comment by ahmadyousafk** [comment]
yes @linzzzzllll 

> > 我刚刚通过将依赖关系的版本从0.7.26更改为最新的0.8.1来解决此问题。
> 
> 0.8.1 ?

**Comment by caudetgit** [comment]
You can check the Readme for latest version dependency: https://github.com/rive-app/rive-flutter#add-to-pubspecyaml
