### ISSUE TITLE
Linux output

### ISSUE THREAD

**Issue by alirezabashi98** [rive-app/rive-flutter#311]
Rive is great, but the only problem is that it is not available for Linux, will it be added later?
And that's the only lack compared to Lottie

**Comment by stMerlHin** [comment]
Any update ?

**Comment by stMerlHin** [comment]
Any update ?

**Comment by hosseinkhojany** [comment]
Any update ?

**Comment by Binozo** [comment]
Same problem here

I get this exception while trying to boot up my App which uses Rive:


```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'init': /home/user/StudioProjects/gtspro_app/build/linux/x64/debug/bundle/lib/libflutter_linux_gtk.so: undefined symbol: init
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      init (package:rive_common/src/rive_text_ffi.dart:528:15)
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:837:3)
#4      Font.initialize (package:rive_common/rive_text.dart:469:12)
#5      RiveFile._initTextAndImport (package:rive/src/rive_file.dart:362:20)
#6      RiveFile.asset (package:rive/src/rive_file.dart:392:12)
<asynchronous suspension>
#7      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:203:11)
<asynchronous suspension>
```

**Comment by ai-and-i** [comment]
See #363, which references a way to build it on linux using community-provided patches.

I would love to see this integrated into the mainline!

**Comment by HayesGordon** [comment]
Closing this and keeping track of this in the related issue: https://github.com/rive-app/rive-flutter/issues/363
