### ISSUE TITLE
Error Rive.cppInitialize

### ISSUE THREAD

**Issue by forYouDevelop** [rive-app/rive-flutter#326]
I have problem with my users after update rive from 0.10.3 to 0.11.3

### Description
Fatal Exception: java.lang.RuntimeException: Unable to create application com.facemassage.ThisApplication: u2.d: java.lang.UnsatisfiedLinkError: No implementation found for void app.rive.runtime.kotlin.core.Rive.cppInitialize() (tried Java_app_rive_runtime_kotlin_core_Rive_cppInitialize and Java_app_rive_runtime_kotlin_core_Rive_cppInitialize__)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6740)
       at android.app.ActivityThread.access$1300(ActivityThread.java:239)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1915)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7680)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

### Steps To Reproduce
- On start the app

tools.build:gradle:7.2.2
ndkVersion "25.1.8937393"
compileSdkVersion 33
buildToolsVersion "30.0.3"

rive: ^0.11.3
Flutter 3.10.5
Dart version 3.0.5
DevTools version 2.23.1

User device: OnePlus8Pro, Android 11
<img width="404" alt="image" src="https://github.com/rive-app/rive-flutter/assets/66330062/fb0b2c88-eb2e-4281-9eb9-21bcd3ba8564">

**Comment by HayesGordon** [comment]
Hi @forYouDevelop sorry for the late reply on this one. Are you still experiencing this issue? 

Some things you can test is to see if you're also experiencing this issue when adding Rive to a new project. If you can provide more information, or a reproducible example we'll be able to assist more.

**Comment by HayesGordon** [comment]
Closing this issue as there has been no reply. It may be related to: https://github.com/rive-app/rive-flutter/issues/403 which has a workaround.
