### ISSUE TITLE
Could not find 'libjnirivebridge.so'. Looked for: [x86], but only found: [].

### ISSUE THREAD

**Issue by forYouDevelop** [rive-app/rive-flutter#332]
We have this issue after update Rive to 4 version

Fatal Exception: java.lang.RuntimeException: Unable to create application com.facemassage.ThisApplication: b3.d: a7.b: Could not find 'libjnirivebridge.so'. Looked for: [x86], but only found: [].
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
       at android.app.ActivityThread.-wrap1()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

rive: ^0.11.4
Flutter version 3.10.5
ndkVersion "25.1.8937393"
compileSdkVersion 33

**Comment by HayesGordon** [comment]
HI @forYouDevelop , what was the previous version you were on? And what platform are you using, windows/linux/macOS?

**Comment by forYouDevelop** [comment]
Hi
I catch this issues on Android.
The latest stable version was rive: ^0.10.3, then we migrated to 0.11.1, and now we use 0.11.4. And now have problems with NDK with rive

**Comment by HayesGordon** [comment]
No I meant from which platform are you building. If you're using Linux, it may be related to the issue mentioned here:
https://github.com/rive-app/rive-flutter/issues/323#issuecomment-1638880701

Please see the [platform_considerations doc](https://github.com/rive-app/rive-flutter/blob/master/platform_considerations.md) for additional information

**Comment by HayesGordon** [comment]
Closing this issue as it's stale and we've updated the build process and how we include these native libs from version `0.14.0-dev.1`.

You can read more here:

- [Migration Guide](https://rive.app/docs/runtimes/flutter/migration-guide)
- [Rive Native for Flutter](https://rive.app/docs/runtimes/flutter/rive-native)
- [Rive Flutter Docs](https://rive.app/docs/runtimes/flutter/flutter)

If you're having issues updating to the latest, please open a new issue with reproducible steps.
