### ISSUE TITLE
Request to Enable Rive Renderer for Flutter Apps (Android, iOS, Web)

### ISSUE THREAD

**Issue by NashIlli** [rive-app/rive-flutter#388]
Hello Rive Team,

A few months ago, Rive launched the Rive Renderer for Android, iOS, and Web. I am thoroughly impressed by the capabilities it provides for creating beautiful and interactive animations.

I primarily work with Flutter for cross-platform development and would love to utilize the Rive Renderer in Flutter apps targeting Android, iOS, and Web. I believe this would be a significant upgrade, enabling developers like myself to create even more immersive experiences.

Could you please enable the Rive Renderer for use in Flutter apps across these platforms?

Thank you for considering this request. It would be incredibly beneficial for developers and enhance the quality of our apps.

Looking forward to your response!

Best regards,

Nash

**Comment by HayesGordon** [comment]
Hi @NashIlli, work for this is underway and we will update the community once this is available.

**Comment by NashIlli** [comment]
Great news @HayesGordon ! Thanks for the update. We are looking forward that update! :)

**Comment by BlockRen** [comment]
Great! Looking forward to Rive Renderer or Impeller related renderer in Flutter for all platforms.
Absolutely necessary for Android and iOS. Excited to see the Renderer in action.

**Comment by MaoHolden** [comment]
Hey guys, just checking out if there has been any update on this issue? Have an awesome day! <3

**Comment by HayesGordon** [comment]
@MaoHolden we should be "silently" launching rive_native to Pub in the next few days for macOS and Windows. There is still work to do to add the other platforms, and before we include it as part of the `rive_flutter` package.

**Comment by Matt319** [comment]
Hello! Has there been any update on this? I checked on pub.dev but I couldn't find any release. Thank you!

**Comment by exploringly** [comment]
Yes, I'd also really appreciate knowing when the River Renderer will be available on Flutter. I guess I'm also a little surprised that the Flutter GameKit was announced as "Your first opportunity to experience the power of the Rive Renderer" (https://rive.app/use-cases/rive-gamekit-for-flutter) yet there still isn't a Flutter version. Based on that announcement one would think Flutter would have been the first available platform. But strangely, the Rive Renderer is now on every other platform *except* Flutter (& Web [WebGL]) (https://rive.app/community/doc/overview/docD20dU9Rod).

Just curious: Why was the River Renderer available as a preview on Flutter first, but then Flutter wound up as seemingly the last platform to get it? Were there some big unexpected technical difficulties with Flutter? Is Flutter going to be a viable way to run Rive Renderer?  **Is Flutter still a major platform for Rive, or is Flutter moving to a less preferred status?**

Really love what your product enables and look forward to seeing the Rive Renderer on Flutter hopefully very soon. Thanks so much and all the best.

**Comment by NashIlli** [comment]
Same thoughts that @exploringly

We really look forward to use Rive Renderer in Flutter.

**Comment by BlockRen** [comment]
Any progress? Looking forward to it.

**Comment by NashIlli** [comment]
> @MaoHolden we should be "silently" launching rive_native to Pub in the next few days for macOS and Windows. There is still work to do to add the other platforms, and before we include it as part of the `rive_flutter` package.

I mentioned this on Discord to a member of the Rive team, but I wanted to share it here for greater visibility and a better chance of success.

From what I understand, the Rive team is currently focused on and debating between prioritizing Vulkan support or implementing OpenGL ES first as a fallback before Vulkan is fully ready. I truly appreciate the effort and work being put into this decision, as it’s a critical step for Android support.

From my research, it's evident that a significant portion of devices, especially older or budget models, still lack Vulkan support. While newer devices are increasingly Vulkan-compatible, many Android users remain on hardware that only supports OpenGL ES.

Introducing a GL implementation as a fallback would not only ensure broader compatibility for low-end devices but also provide a quicker pathway for Android support while Vulkan development continues. If developing a GL implementation is faster than completing Vulkan, it could serve both as a fallback for low-end devices and as a means to bring Android support to the Rive Runtime sooner.

This approach would significantly increase accessibility and adoption by ensuring the Rive Runtime can run on a wide range of devices while still working toward the performance benefits Vulkan offers in the long term.

While Vulkan is exciting for high-performance use cases and modern devices, relying on it exclusively won't provide a comprehensive solution for Android or "any" device. Many devices, especially in lower markets, will be excluded, limiting Rive’s reach and usability. OpenGL ES as a fallback would help bridge the gap and make the Runtime truly versatile across the Android ecosystem.

Thanks, and pardon me if I misunderstood or said anything incorrect about the Rive team’s plans. We are truly excited about this feature and looking forward to its release. However, we are also concerned that if it only supports Vulkan-compatible devices, it might become more of a problem than a solution for us.

**Comment by Smirnovious** [comment]
Looking Forward to it! can't wait to use the scrolling feature :)

**Comment by Nicola-Cestaro** [comment]
Any progress? We started using more complex animations and they are all laggy on low-end Android devices

**Comment by NashIlli** [comment]
Same @Nicola-Cestaro

**Comment by damywise** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/135930538?v=4&amp;size=80">@MaoHolden](https://github.com/MaoHolden) we should be "silently" launching rive_native to Pub in the next few days for macOS and Windows. There is still work to do to add the other platforms, and before we include it as part of the `rive_flutter` package.

There's a technical preview package but no updates since 2 months ago, and I don't see them announcing it outside of Discord
https://pub.dev/packages/rive_native

It seem to work but I haven't tested on mobile device

Maybe we should try it and give feedback so the team can improve it?

**Comment by HayesGordon** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/135930538?v=4&amp;size=80">@MaoHolden](https://github.com/MaoHolden) we should be "silently" launching rive_native to Pub in the next few days for macOS and Windows. There is still work to do to add the other platforms, and before we include it as part of the `rive_flutter` package.
> 
> There's a technical preview package but no updates since 2 months ago, and I don't see them announcing it outside of Discord https://pub.dev/packages/rive_native
> 
> It seem to work but I haven't tested on mobile device
> 
> Maybe we should try it and give feedback so the team can improve it?

Work is still underway! And feedback any feedback is appreciated!

**Comment by Nicola-Cestaro** [comment]
Knowing a timeline for the Android release for rive_native would help us a lot

**Comment by Smirnovious** [comment]
Any news on this?? @HayesGordon

**Comment by orestesgaolin** [comment]
I wasn't able to build app with`rive_native 0.0.1-dev.6` and Flutter 3.29.2. Let me know if you'd like to receive a dedicated bug report.


### iOS

After running the setup script `dart run rive_native:setup --verbose --clean --platform ios`  and building the app in debug mode:

```
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: ReadWriteRing::currentRead()
Error (Xcode): Undefined symbol: ReadWriteRing::nextRead()
Error (Xcode): Undefined symbol: ReadWriteRing::ReadWriteRing()
Error (Xcode): Undefined symbol: _createRiveRenderer
Error (Xcode): Undefined symbol: _createRiveRendererContext
Error (Xcode): Undefined symbol: _destroyRiveRenderer
Error (Xcode): Undefined symbol: _destroyRiveRendererContext
Error (Xcode): Undefined symbol: _setGPU
Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
```

### Android

On Android the issue seems to be with the c compiler, which is odd because I also run the setup script for android.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rive_native:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Users/dominik/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Configuring incomplete, errors occurred!
  See also "/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/.cxx/Debug/5f2218l2/arm64-v8a/CMakeFiles/CMakeOutput.log".

  C++ build system [configure] failed while executing:
      /Users/dominik/Library/Android/sdk/cmake/3.22.1/bin/cmake \
        -H/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=21 \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393 \
        -DCMAKE_ANDROID_NDK=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393 \
        -DCMAKE_TOOLCHAIN_FILE=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/Users/dominik/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dominik/Projects/redacted/redacted-app/build/rive_native/intermediates/cxx/Debug/5f2218l2/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/dominik/Projects/redacted/redacted-app/build/rive_native/intermediates/cxx/Debug/5f2218l2/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -B/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/.cxx/Debug/5f2218l2/arm64-v8a \
        -GNinja
    from /Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android
  Cannot operate on packages inside the cache.
  #0      fail (package:pub/src/utils.dart:567:5)
  #1      new Entrypoint (package:pub/src/entrypoint.dart:337:7)
  #2      getExecutableForCommand (package:pub/src/executable.dart:404:24)
  <asynchronous suspension>
  #3      RunCommand.run (package:dartdev/src/commands/run.dart:406:20)
  <asynchronous suspension>
  #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
  <asynchronous suspension>
  #5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:18)
  <asynchronous suspension>
  #6      runDartdev (package:dartdev/dartdev.dart:47:16)
  <asynchronous suspension>
  #7      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:13:5)
  <asynchronous suspension>

  CMake Error at CMakeLists.txt:15 (message):
    Failed to run rive_native setup command

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
```

**Comment by HayesGordon** [comment]
> I wasn't able to build app with`rive_native 0.0.1-dev.6` and Flutter 3.29.2. Let me know if you'd like to receive a dedicated bug report.
> 
> ### iOS
> After running the setup script `dart run rive_native:setup --verbose --clean --platform ios` and building the app in debug mode:
> 
> ```
> Failed to build iOS app
> Could not build the precompiled application for the device.
> Error (Xcode): Undefined symbol: ReadWriteRing::currentRead()
> Error (Xcode): Undefined symbol: ReadWriteRing::nextRead()
> Error (Xcode): Undefined symbol: ReadWriteRing::ReadWriteRing()
> Error (Xcode): Undefined symbol: _createRiveRenderer
> Error (Xcode): Undefined symbol: _createRiveRendererContext
> Error (Xcode): Undefined symbol: _destroyRiveRenderer
> Error (Xcode): Undefined symbol: _destroyRiveRendererContext
> Error (Xcode): Undefined symbol: _setGPU
> Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> ```
> 
> ### Android
> On Android the issue seems to be with the c compiler, which is odd because I also run the setup script for android.
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':rive_native:configureCMakeDebug[arm64-v8a]'.
> > [CXX1429] error when building with cmake using /Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
>   -- Detecting C compiler ABI info
>   -- Detecting C compiler ABI info - done
>   -- Check for working C compiler: /Users/dominik/Library/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang - skipped
>   -- Detecting C compile features
>   -- Detecting C compile features - done
>   -- Configuring incomplete, errors occurred!
>   See also "/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/.cxx/Debug/5f2218l2/arm64-v8a/CMakeFiles/CMakeOutput.log".
> 
>   C++ build system [configure] failed while executing:
>       /Users/dominik/Library/Android/sdk/cmake/3.22.1/bin/cmake \
>         -H/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android \
>         -DCMAKE_SYSTEM_NAME=Android \
>         -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
>         -DCMAKE_SYSTEM_VERSION=21 \
>         -DANDROID_PLATFORM=android-21 \
>         -DANDROID_ABI=arm64-v8a \
>         -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
>         -DANDROID_NDK=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393 \
>         -DCMAKE_ANDROID_NDK=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393 \
>         -DCMAKE_TOOLCHAIN_FILE=/Users/dominik/Library/Android/sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake \
>         -DCMAKE_MAKE_PROGRAM=/Users/dominik/Library/Android/sdk/cmake/3.22.1/bin/ninja \
>         -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dominik/Projects/redacted/redacted-app/build/rive_native/intermediates/cxx/Debug/5f2218l2/obj/arm64-v8a \
>         -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/dominik/Projects/redacted/redacted-app/build/rive_native/intermediates/cxx/Debug/5f2218l2/obj/arm64-v8a \
>         -DCMAKE_BUILD_TYPE=Debug \
>         -B/Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android/.cxx/Debug/5f2218l2/arm64-v8a \
>         -GNinja
>     from /Users/dominik/.pub-cache/hosted/pub.dev/rive_native-0.0.1-dev.6/android
>   Cannot operate on packages inside the cache.
>   #0      fail (package:pub/src/utils.dart:567:5)
>   #1      new Entrypoint (package:pub/src/entrypoint.dart:337:7)
>   #2      getExecutableForCommand (package:pub/src/executable.dart:404:24)
>   <asynchronous suspension>
>   #3      RunCommand.run (package:dartdev/src/commands/run.dart:406:20)
>   <asynchronous suspension>
>   #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
>   <asynchronous suspension>
>   #5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:240:18)
>   <asynchronous suspension>
>   #6      runDartdev (package:dartdev/dartdev.dart:47:16)
>   <asynchronous suspension>
>   #7      main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:13:5)
>   <asynchronous suspension>
> 
>   CMake Error at CMakeLists.txt:15 (message):
>     Failed to run rive_native setup command
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 19s
> ```
> 
> **Edit**
> 
> I managed to build it on my Android (Samsung S21, Android 14) device when used direct path to rive_native instead of referencing it from pub.dev. iOS wouldn't compile anyway.
> 
> rive_native:
>   path: "../rive_native-0.0.1-dev.6"
> However, it got stuck on the splash screen now (with Impeller disabled on Android). If that's not a known issue, I'm happy to provide more details. Removing rive_native resolved the issue.

@orestesgaolin let's add this information to this issue: https://github.com/rive-app/rive-flutter/issues/460

Which appears to be similar.

I posted some step you can try there to see if it helps. I'd recommend trying a `flutter clean`, then downloading the libs, and then running your app. Could you also confirm if you're able to run the example app that is in `rive_native`?

**Comment by mklemann90** [comment]
> An update here that the Rive Renderer is now available for iOS, Android, macOS, Windows, and Web.
> 
> For more information see: https://rive.app/docs/runtimes/flutter/rive-native
> 
> This new package `rive_native` will be added in version 0.14.0 of Rive Flutter. But if you want to use the Rive Renderer and the latest Rive features, we recommend using `rive_native` today.

Hi @HayesGordon do you have any rough idea when rive package 0.14.0 will be released? We would like to use some rive features in our app that are only supported for rive renderer. Migrating our whole app to rive-native would be a big effort so it would help a lot to know when to expect rive 0.14.0 to decide on whether or invest work into the migration to have access to those features sooner.

A really rough estimation would already help. Will it take just a few more days? A few more weeks? A few more months?

Thanks already ahead.

**Comment by nateshmbhat** [comment]
what will be the size increase for the app (apk size) when you add the rive renderer to flutter's `rive_flutter` package ?

**Comment by mszczesniak94** [comment]
> I wasn't able to build app with`rive_native 0.0.1-dev.6` and Flutter 3.29.2. Let me know if you'd like to receive a dedicated bug report.
> 
> ### iOS
> After running the setup script `dart run rive_native:setup --verbose --clean --platform ios` and building the app in debug mode:
> 
> ```
> Failed to build iOS app
> Could not build the precompiled application for the device.
> Error (Xcode): Undefined symbol: ReadWriteRing::currentRead()
> Error (Xcode): Undefined symbol: ReadWriteRing::nextRead()
> Error (Xcode): Undefined symbol: ReadWriteRing::ReadWriteRing()
> Error (Xcode): Undefined symbol: _createRiveRenderer
> Error (Xcode): Undefined symbol: _createRiveRendererContext
> Error (Xcode): Undefined symbol: _destroyRiveRenderer
> Error (Xcode): Undefined symbol: _destroyRiveRendererContext
> Error (Xcode): Undefined symbol: _setGPU
> Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> ```
> 

I had the same issue on iOS with Flutter 3.35.1 and rive: ^0.14.0-dev.6.
I solved it by changing the Podfile linking from:
```
`use_frameworks! :linkage => :static`
```

to

```
`use_frameworks!`
```

FYI @HayesGordon I think there still might be something wrong with the static linking on iOS.
