### ISSUE TITLE
Failed build for Flutter Web WASM

### ISSUE THREAD

**Issue by ekasetiawans** [rive-app/rive-flutter#391]
I using the latest stable flutter version
Here is the log when I run `flutter build web --wasm`

```
ekasetiawans@MacBookPro admin % flutter build web --wasm            

┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/wasm for more information.                                     │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
*NOTE*: Compilation to WasmGC is experimental.
The support may change, or be removed, with no advance notice.


Unhandled exception:
Constant InstanceConstant(const _FfiAbiSpecificMapping{_FfiAbiSpecificMapping.nativeTypes: const <Type?>[Uint32, Uint64, Uint32, Uint64, Uint64, Uint64, Uint64, Uint64, Uint32, Uint64,
Uint64, Uint32, Uint64, Uint32, Uint64, Uint32, Uint64, Uint64, Uint64, Uint64, Uint32, Uint64]}) references field _FfiAbiSpecificMapping.nativeTypes which is not retained
#0      _TreeShakerConstantVisitor.visitInstanceConstant.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:2257)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#2      _TreeShakerConstantVisitor.visitInstanceConstant (package:vm/transformations/type_flow/transformer.dart:2255)
#3      InstanceConstant.accept (package:kernel/ast.dart:14144)
#4      _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#5      _TreeShakerConstantVisitor.visitInstanceConstant.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:2260)
#6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#7      _TreeShakerConstantVisitor.visitInstanceConstant (package:vm/transformations/type_flow/transformer.dart:2255)
#8      InstanceConstant.accept (package:kernel/ast.dart:14144)
#9      _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#10     _TreeShakerPass1.visitConstant (package:vm/transformations/type_flow/transformer.dart:1558)
#11     ConstantExpression.transformOrRemoveChildren (package:kernel/ast.dart:8723)
#12     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#13     TreeVisitor1Default.defaultExpression (package:kernel/visitor.dart:739)
#14     ExpressionVisitor1DefaultMixin.visitConstantExpression (package:kernel/visitor.dart:2368)
#15     ConstantExpression.accept1 (package:kernel/ast.dart:8707)
#16     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#17     RemovingTransformer.transformList (package:kernel/visitor.dart:2141)
#18     RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:2067)
#19     TreeShaker.addClassUsedInType (package:vm/transformations/type_flow/transformer.dart:878)
#20     _TreeShakerTypeVisitor.visitInterfaceType (package:vm/transformations/type_flow/transformer.dart:1098)
#21     InterfaceType.accept (package:kernel/ast.dart:11536)
#22     _TreeShakerConstantVisitor.visitTypeLiteralConstant (package:vm/transformations/type_flow/transformer.dart:2287)
#23     TypeLiteralConstant.accept (package:kernel/ast.dart:14548)
#24     _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#25     _TreeShakerConstantVisitor.visitSetConstant (package:vm/transformations/type_flow/transformer.dart:2209)
#26     ListConstant.accept (package:kernel/ast.dart:13886)
#27     _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#28     _TreeShakerConstantVisitor.visitInstanceConstant.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:2260)
#29     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#30     _TreeShakerConstantVisitor.visitInstanceConstant (package:vm/transformations/type_flow/transformer.dart:2255)
#31     InstanceConstant.accept (package:kernel/ast.dart:14144)
#32     _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#33     _TreeShakerConstantVisitor.visitInstanceConstant.<anonymous closure> (package:vm/transformations/type_flow/transformer.dart:2260)
#34     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#35     _TreeShakerConstantVisitor.visitInstanceConstant (package:vm/transformations/type_flow/transformer.dart:2255)
#36     InstanceConstant.accept (package:kernel/ast.dart:14144)
#37     _TreeShakerConstantVisitor.analyzeConstant (package:vm/transformations/type_flow/transformer.dart:2190)
#38     _TreeShakerPass1.visitConstant (package:vm/transformations/type_flow/transformer.dart:1558)
#39     ConstantExpression.transformOrRemoveChildren (package:kernel/ast.dart:8723)
#40     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#41     TreeVisitor1Default.defaultExpression (package:kernel/visitor.dart:739)
#42     ExpressionVisitor1DefaultMixin.visitConstantExpression (package:kernel/visitor.dart:2368)
#43     ConstantExpression.accept1 (package:kernel/ast.dart:8707)
#44     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#45     RemovingTransformer.transformList (package:kernel/visitor.dart:2141)
#46     RemovingTransformer.transformExpressionList (package:kernel/visitor.dart:2067)
#47     TreeShaker.addClassUsedInType (package:vm/transformations/type_flow/transformer.dart:878)
#48     _TreeShakerTypeVisitor.visitInterfaceType (package:vm/transformations/type_flow/transformer.dart:1098)
#49     InterfaceType.accept (package:kernel/ast.dart:11536)
#50     visitList (package:kernel/ast.dart:14913)
#51     InterfaceType.visitChildren (package:kernel/ast.dart:11545)
#52     _TreeShakerTypeVisitor.visitInterfaceType (package:vm/transformations/type_flow/transformer.dart:1099)
#53     InterfaceType.accept (package:kernel/ast.dart:11536)
#54     _TreeShakerPass1.visitDartType (package:vm/transformations/type_flow/transformer.dart:1247)
#55     VariableDeclaration.transformOrRemoveChildren (package:kernel/ast.dart:10817)
#56     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#57     TreeVisitor1Default.defaultExpression (package:kernel/visitor.dart:739)
#58     StatementVisitor1DefaultMixin.visitVariableDeclaration (package:kernel/visitor.dart:2597)
#59     VariableDeclaration.accept1 (package:kernel/ast.dart:10795)
#60     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#61     RemovingTransformer.transformList (package:kernel/visitor.dart:2141)
#62     RemovingTransformer.transformStatementList (package:kernel/visitor.dart:2095)
#63     AssertBlock.transformOrRemoveChildren (package:kernel/ast.dart:9311)
#64     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#65     TreeVisitor1Default.defaultExpression (package:kernel/visitor.dart:739)
#66     StatementVisitor1DefaultMixin.visitBlock (package:kernel/visitor.dart:2546)
#67     Block.accept1 (package:kernel/ast.dart:9250)
#68     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#69     RemovingTransformer.transformOrRemoveStatement (package:kernel/visitor.dart:1899)
#70     FunctionNode.transformOrRemoveChildren (package:kernel/ast.dart:3950)
#71     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#72     TreeVisitor1DefaultMixin.visitFunctionNode (package:kernel/visitor.dart:693)
#73     FunctionNode.accept1 (package:kernel/ast.dart:3902)
#74     RemovingTransformer.transform (package:kernel/visitor.dart:1881)
#75     Procedure.transformOrRemoveChildren (package:kernel/ast.dart:3284)
#76     _TreeShakerPass1.defaultMember (package:vm/transformations/type_flow/transformer.dart:1297)
#77     MemberVisitor1DefaultMixin.visitProcedure (package:kernel/visitor.dart:432)
#78     Procedure.accept1 (package:kernel/ast.dart:3258)
#79     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#80     RemovingTransformer.transformList (package:kernel/visitor.dart:2141)
#81     RemovingTransformer.transformProcedureList (package:kernel/visitor.dart:2033)
#82     Library.transformOrRemoveChildren (package:kernel/ast.dart:625)
#83     RemovingTransformer.defaultTreeNode (package:kernel/visitor.dart:2164)
#84     TreeVisitor1DefaultMixin.visitLibrary (package:kernel/visitor.dart:680)
#85     Library.accept1 (package:kernel/ast.dart:588)
#86     RemovingTransformer.transformOrRemove (package:kernel/visitor.dart:1917)
#87     RemovingTransformer.transformList (package:kernel/visitor.dart:2141)
#88     RemovingTransformer.transformLibraryList (package:kernel/visitor.dart:1960)
#89     Component.transformOrRemoveChildren (package:kernel/ast.dart:14779)
#90     _TreeShakerPass1.transformComponent (package:vm/transformations/type_flow/transformer.dart:1156)
#91     TreeShaker.transformComponent (package:vm/transformations/type_flow/transformer.dart:831)
#92     transformComponent (package:vm/transformations/type_flow/transformer.dart:134)
#93     compileToModule (package:dart2wasm/compile.dart:156)
<asynchronous suspension>
#94     generateWasm (package:dart2wasm/generate_wasm.dart:24)
<asynchronous suspension>
#95     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/dart2wasm/bin/dart2wasm.dart:10)
<asynchronous suspension>
  Command: /Users/ekasetiawans/Development/flutter/bin/cache/dart-sdk/bin/dart compile wasm --packages=.dart_tool/package_config.json
  --extra-compiler-option=--dart-sdk=/Users/ekasetiawans/Development/flutter/bin/cache/dart-sdk
  --extra-compiler-option=--platform=/Users/ekasetiawans/Development/flutter/bin/cache/flutter_web_sdk/kernel/dart2wasm_platform.dill
  --extra-compiler-option=--delete-tostring-package-uri=dart:ui --extra-compiler-option=--delete-tostring-package-uri=package:flutter --extra-compiler-option=--import-shared-memory
  --extra-compiler-option=--shared-memory-max-pages=32768 -Ddart.vm.product=true
  -DFLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/f6344b75dcf861d8bf1f1322780b8811f982e31a/ -DFLUTTER_WEB_AUTO_DETECT=false -DFLUTTER_WEB_USE_SKIA=false
  -DFLUTTER_WEB_USE_SKWASM=true --extra-compiler-option=--depfile=/Users/ekasetiawans/Projects/TigaPutri/admin/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/dart2wasm.d -O4
  --no-name-section -o /Users/ekasetiawans/Projects/TigaPutri/admin/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart.wasm
  /Users/ekasetiawans/Projects/TigaPutri/admin/.dart_tool/flutter_build/2bc6bf09fa388c3aa3580c6c6256f0e7/main.dart
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:125:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:321:19)
<asynchronous suspension>
#2      Dart2WasmTarget.build (package:flutter_tools/src/build_system/targets/web.dart:329:5)
<asynchronous suspension>
#3      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:875:9)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#6      Future.wait.<anonymous closure> (dart:async/future.dart:524:21)
<asynchronous suspension>
#7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:813:32)
<asynchronous suspension>
#8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:642:16)
<asynchronous suspension>
#9      WebBuilder.buildWeb (package:flutter_tools/src/web/compile.dart:92:34)
<asynchronous suspension>
#10     BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:230:5)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#13     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
<asynchronous suspension>
#19     main (package:flutter_tools/executable.dart:93:3)
<asynchronous suspension>

Compiling lib/main.dart for the Web...                             88.2s
Error: Failed to compile application for the Web.
```

Here is log without rive:
```
ekasetiawans@MacBookPro admin % flutter build web --wasm        

┌─ New feature ────────────────────────────────────────────────────────────────────────────┐
│   WebAssembly compilation is new. Understand the details before deploying to production. │
│   See https://flutter.dev/wasm for more information.                                     │
└──────────────────────────────────────────────────────────────────────────────────────────┘

Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 257628 to 3288 bytes (98.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when
building your app.
Font asset "Ionicons.ttf" was tree-shaken, reducing it from 441724 to 397192 bytes (10.1% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when
building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 13916 bytes (99.2% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons
flag when building your app.
Compiling lib/main.dart for the Web...                            187.4s
✓ Built build/web
```

My Flutter Doctor:
```
ekasetiawans@MacBookPro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.4.1 23E224 darwin-x64, locale en-ID)
    • Flutter version 3.22.0 on channel stable at /Users/ekasetiawans/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5dcb86f68f (6 days ago), 2024-05-09 07:39:20 -0500
    • Engine revision f6344b75dc
    • Dart version 3.4.0
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ekasetiawans/Development/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ekasetiawans/Development/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.88.0

[✓] Connected device (3 available)
    • iPhone 11 (mobile) • 00008030-0004385C1498C02E • ios            • iOS 17.4.1 21E236
    • macOS (desktop)    • macos                     • darwin-x64     • macOS 14.4.1 23E224 darwin-x64
    • Chrome (web)       • chrome                    • web-javascript • Google Chrome 124.0.6367.202

[✓] Network resources
    • All expected network resources are available.

• No issues found!
ekasetiawans@MacBookPro ~ % 
```

Rive version : `rive: ^0.13.4`

**Comment by renefloor** [comment]
Had to disable Rive animations here, but you can use it as an example project that fails with the same error: 
https://github.com/renefloor/flutter_puzzle_hack/pull/5/files

disabled animations are `boat.dart`, `submarine.dart` and `_BannerAnimation` in `puzzle_page.dart`.

**Comment by r-durao-pvotal** [comment]
We're also facing the same issue with Flutter 3.22.0 and rive 0.11.17

**Comment by NashIlli** [comment]
+1

**Comment by YawarOsman** [comment]
Same problem with `desktop_drop`, `flutter_secure_storage`, and `crop_image`

**Comment by HayesGordon** [comment]
Hey all, the Rive Flutter package **v0.13.5** addresses this and now uses `dart:js_interop` and `package:web` APIs.

Please reopen if you encounter any difficulties.
