### ISSUE TITLE
iOS Rive initialization crash: init -> rive_text_ffi not found

### ISSUE THREAD

**Issue by julianfalcionelli** [rive-app/rive-flutter#432]
### Description

On iOS my rive animations are failing on initialization.

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found
flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      init (package:rive_common/src/rive_text_ffi.dart:497:16)
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:814:3)
#4      Font.initialize (package:rive_common/rive_text.dart:463:7)
#5      RiveFile.initialize (package:rive/src/rive_file.dart:392:33)
#6      RiveFile._initTextAndImport (package:rive/src/rive_file.dart:414:13)
#7      RiveFile.asset (package:rive/src/rive_file.dart:444:12)
<asynchronous suspension>
#8      RiveAnimationState._configure (package:rive/src/widgets/rive_animation.dart:212:11)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

**On Android this is working as expected.**

### Rive version

`rive: ^0.13.16`

### Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.3, on macOS 14.1.2 23B92 darwin-x64, locale en-AR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.93.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Julian’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources
```

### Rive File

[get_started.riv.zip](https://github.com/user-attachments/files/17748565/get_started.riv.zip)

### Code

```
....

SizedBox(
            height: 400,
            child: RiveAnimation.asset(
              'assets/animations/rive/get_started.riv',
              artboard: 'Artboard',
              onInit: _onRiveInit,
            ),
          ),
....

  void _onRiveInit(Artboard artboard) {
    final controller =
        StateMachineController.fromArtboard(artboard, 'State Machine 1', onStateChange: (stateMachine, state) {
      LogHelper.d('State: $stateMachine -> $state');
      if (state == 'ExitState') {
        context.read<InitialBloc>().add(const InitialEvent.onGetStartedClicked());
      }
      if (state == 'Exit') {
        setState(() {
          _accessAccountOpacity = 0.0;
        });
      }
      if (state == 'KidsBlink') {
        setState(() {
          _accessAccountOpacity = 1.0;
        });
      }
    });
    if (controller == null) {
      LogHelper.e('State machine not found');
      return;
    }
    artboard.addController(controller);
    _controller = controller;
  }

```

**Comment by HayesGordon** [comment]
Hi @julianfalcionelli, is this failing for you locally?

- Which version of Flutter are you using?
- What device is this reproducing on?

Can you try running `flutter clean` and rebuilding.

You can also try initializing Rive earlier in your app lifecycle. For example, at the start of `main`:
```
void main() {
  /// Initialize Rive's text, audio, and layout engines.
  /// This will automatically be called the first time a RiveFile is loaded if
  /// it has not been initialized. And does not need to be called.
  ///
  /// However, calling it early here makes the first
  /// visible Rive graphic load faster.
  unawaited(RiveFile.initialize());

...
  }

**Comment by julianfalcionelli** [comment]
Hi @HayesGordon , thanks for your reply.

My Flutter version is:

```
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (9 weeks ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3
```

We can reproduce this in all the iOS devices we have (I can get you the list of models and iOS versions next week since I have to contact QA), for me I am testing on an iPhone SE and emulator (iPhone 15 Pro  - iOS 17).


I tried by cleaning everything and rebuilding (`flutter clean`).

I also tried calling the `RiveFile.initialize()` as you said but I got the same error when calling that function:

```
flutter: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found
flutter: 
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      init (package:rive_common/src/rive_text_ffi.dart:497:16)
#2      init (package:rive_common/src/rive_text_ffi.dart)
#3      initFont (package:rive_common/src/rive_text_ffi.dart:814:3)
#4      Font.initialize (package:rive_common/rive_text.dart:463:7)
#5      RiveFile.initialize (package:rive/src/rive_file.dart:392:33)
#6      LoadDependenciesGraphWidget.setupDependenciesGraph (package:earthrangers/ui/app/app.dart:190:20)
<asynchronous suspension>
```

**Comment by HayesGordon** [comment]
We've not been able to reproduce this issue, and I'm trying to isolate the cause.

Are you potentially overriding the `rive_common` package in your pubspec to be a particular version?

It'll be incredibly helpful if you can provide a small example project that reproduces this that we can run. And if you can provide info on the following:
- Does this reproduce in a new project for you?
- Does it only reproduce for release builds, or can you verify this error locally?
- Did this break after a certain version of Rive Flutter, or are you adding Rive for the first time?

I see there is a similar issue on the Dart repository, can you experiment with this suggestion to see if it works for you: https://github.com/dart-lang/native/issues/897#issuecomment-1894150054

**Comment by julianfalcionelli** [comment]
Hi @HayesGordon,

I am using the latest `rive: ^0.13.20` package, I am not overriding any `rive_common` package (on Android is working fine, so I don't think it could be related to that).

- I haven't tried a new project yet.
- This is happening on Release and Debug builds.
- I am adding Rive for the first time.

I also found that thread you mentioned there and tried changing that from XCode but didn't work. 

I am now updating XCode to the latest version and try again.

**Comment by Kal-Elx** [comment]
Hi, this problem has recently surfaced in our app as well and we can reproduce it on all iOS devices in release, TestFlight and debug builds. 

We are using
- flutter: 3.27.1
- xcode 16.2
- rive: 0.13.20

I've tried to call `RiveFile.initialize()` during app initialization which makes the error appear when that code is called instead of when a rive animation is built. 

I also tried to change Strip Style from "All Symbols" to "Non-Global Symbols" according to https://github.com/dart-lang/native/issues/897#issuecomment-1894150054 but no difference.

**Comment by Kal-Elx** [comment]
@HayesGordon I tried to create a small example project to reproduce the issue but unfortunately it works then which explains why you can't reproduce it. This means that the problem most likely lies with bigger/older projects or is caused by some other dependency. 

Let me know if there is anything I can do to help you debug this further.

**Comment by Kal-Elx** [comment]
We bisected our history and found the commit that caused the issue. It configured CocoaPods to use static frameworks instead of dynamic ones.

To reproduce:
- Create a new flutter project
- Add rive as a dependency
- Open `ios/Podfile` and then replace `use_frameworks!` with `use_frameworks! :linkage => :static`.
- Initialize rive by e.g.
```
import 'package:rive/rive.dart';

void main() {
  unawaited(RiveFile.initialize());
  runApp(const MyApp());
}
```

This will lead to the error `Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'init': dlsym(RTLD_DEFAULT, init): symbol not found`.

@julianfalcionelli @dimnocode Can this be what you did as well and reverting it would fix your issue?

**Comment by julianfalcionelli** [comment]
@Kal-Elx thank you for following this, your comment was very useful, since the project I am working on is 5 years old is kind of complicated testing like that.

I removed this `use_frameworks! :linkage => :static` and after that I was getting error "include of non-modular header inside framework module 'firebase_core.FLTFirebasePlugin'", but I was able to fix that by changing the following Setting in the iOS Project:

Xcode => Runner => Build Settings: Search for "Allow Non-modular Includes In Framework Modules" to "yes"

and now is working as expected.

cc: @HayesGordon

**Comment by dimnocode** [comment]
Hi @Kal-Elx,

It was indeed the issue for my case too.

Thank you very much all

**Comment by Tom3652** [comment]
the problem is that i need `use_frameworks! :linkage => :static` for google mobile ads...

**Comment by HayesGordon** [comment]
Glad you all got it resolved.

Closing this issue as it's quite stale and we've made updates to the build process and how we include the native libs from version `0.14.0-dev.1`.

You can read more here:

- [Migration Guide](https://rive.app/docs/runtimes/flutter/migration-guide)
- [Rive Native for Flutter](https://rive.app/docs/runtimes/flutter/rive-native)
- [Rive Flutter Docs](https://rive.app/docs/runtimes/flutter/flutter)

If you're having issues updating to the latest, please open a new issue with reproducible steps.

**Comment by smoketh** [comment]
Here. From another github issue - if you need a specifically linked static library - you can do something like this (helped me to mitigate use of yandex ads) - put that into Podfile, editing `target 'Runner' do` directive and change $static_framework array to libraries which you need. 
```ruby
target 'Runner' do
  use_frameworks!
$static_framework = ['YandexMobileAds', 'yandex_mobileads']

pre_install do |installer|
    installer.pod_targets.each do |pod|
        if $static_framework.include?(pod.name)
            puts "Overriding the #{pod.name} library linking to static linking"
            def pod.build_type;
              Pod::BuildType.static_framework
            end
        end
    end
  end
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end
```

**Comment by giiiita** [comment]
https://github.com/rive-app/rive-flutter/issues/432#issuecomment-2614308228

I’d like to ask how this issue was resolved.

I’m facing a very similar problem when using rive (0.14.0) together with unity_levelplay_mediation (9.0.1).

Because of unity_levelplay_mediation, I need to enable the following setting in my Podfile:

`use_frameworks! :linkage => :static`


However, when this is enabled, rive fails to build and results in linker/build errors.

Since use_frameworks! :linkage => :static seems to be required as long as unity_levelplay_mediation is used, I’m not sure how to resolve this conflict.

Could you please share how this issue was fixed, or if there is a recommended workaround to make rive work with static frameworks enabled?
